site_name: NanoBot-Dev Documentation 🤖
site_description: Documentation for the NanoBot-Dev project
site_url: https://worldlycode.github.io/nanobot-dev-docs
repo_name: nanobot-dev

# Standard docs directory
docs_dir: docs

theme:
  name: material
  font: 
    text: Roboto
    code: Roboto Mono
  # icon:
  #   logo: octicons/globe/16
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    # - toc.integrate
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.details
  - admonition
  - toc:
      permalink: true
      # baselevel: 2
      # separator: "_"
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Setup:
    - Installation: setup/00-index-setup.md
    - 01-Environment Variables: setup/env-config.md
    - 02-Logfire: setup/logfire-setup.md
    - 03-Neon: setup/neon-setup.md
    - 04-Local Database: setup/postgres-local-setup.md
    - 05-Database Tables: setup/database-table-setup.md
    - 06-Running NanoBot: setup/running-nanobot.md
  - User Guide:
    - Overview: user-guide/00-index-user-guide.md
    - Settings Configuration: user-guide/settings.md
    - Document Conversion: user-guide/document-conversion.md
    - Document Chunking: user-guide/document-chunking.md
    - Document Processing Script: user-guide/document-processor.md
    - What is in Utils: user-guide/utils.md
    - Coding with Tests: user-guide/tests.md
    - Collaborating with Git: user-guide/git.md
    - Vector Search: user-guide/vector-search.md
  - API Reference:
    - Database: api/database.md
    - Services: api/services.md
  - Examples: examples.md
  - Blog: 
    - Welcome!: blog/00-index-blog.md
    - Choosing MkDocs: blog/mkdocs.md    
    - Markdown Cheatsheet: blog/markdown.md
    - Understanding Docling: blog/docling.md
    - Logging with Python: blog/logging.md
    - Packages and Imports: blog/packages-and-imports.md
    - Configuring pgAdmin: blog/pgadmin.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/worldlycode/nanobot-dev-docs
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/worldlycode/

copyright: "© 2025 WorldlyCode"
